[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_20", "vips", "pkg-config"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm rebuild sharp", "npm run build"]

[start]
cmd = "npm start"
